#undef  DIODE_DIRECTION
#define DIODE_DIRECTION COL2ROW
/* #undef MATRIX_COL_PINS
#define MATRIX_COL_PINS { GP4, GP5, GP6, GP7, GP8, GP9 }
#undef MATRIX_ROW_PINS
#define MATRIX_ROW_PINS { GP27, GP26, GP22, GP20, GP23, GP21 }
#undef SOFT_SERIAL_PIN
#define SOFT_SERIAL_PIN GP3 */

/* Handedness. */
#define MASTER_LEFT
#define SPLIT_USB_DETECT
#define SPLIT_USB_TIMEOUT_POLL 10

/* VBUS detection. 
#define USB_VBUS_PIN GP19 */

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U
