/* Handedness. */
#define MASTER_RIGHT
#define SPLIT_USB_DETECT
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT

#define POINTING_DEVICE_ROTATION_90
// #define POINTING_DEVICE_INVERT_X
// #define POINTING_DEVICE_INVERT_Y
#define CIRQUE_PINNACLE_DIAMETER_MM 40
#define CIRQUE_PINNACLE_TAP_ENABLE
#define POINTING_DEVICE_GESTURES_SCROLL_ENABLE
#define CIRQUE_PINNACLE_ADDR 0x2A

#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN D1
// #define I2C1_SDA_PAL_MODE 4
#define I2C1_SCL_PIN D0
// #define I2C1_SCL_PAL_MODE 4

/* CRC. */
#define CRC8_USE_TABLE
#define CRC8_OPTIMIZE_SPEED */
